### ISSUE TITLE
Requesting Push and Pull Access 

### ISSUE THREAD

**Issue by shanikadhettige** [Vizzuality/community-mapping#24]
Hi @andresgnlez,

Could I get push/pull access for the community-mapping repo? I am unable to have my pull requests go to the community-mapping master and also unable to upload images to the source folder so that I can include them.

Thanks

![community-mapping screen shot](https://cloud.githubusercontent.com/assets/17725960/16131835/6231c9b2-33de-11e6-83d7-357c726af5eb.png)

**Comment by andresgnlez** [comment]
Ops, sorry for that. Now you are collaborator with write permissions, you should be able to push changes.

**Comment by shanikadhettige** [comment]
Hi @andresgnlez but still for whatever reason it says I do not have write access. 
![write access screenshot](https://cloud.githubusercontent.com/assets/17725960/16149639/308fef60-3460-11e6-96be-de59c2e6b5bd.png)

**Comment by shanikadhettige** [comment]
I had the access to push the requests and it had said that they were merged and also waited a few days to see if there was a lag but still the content is not showing up:

![empty community mapping screenshot](https://cloud.githubusercontent.com/assets/17725960/16231151/f745c320-3792-11e6-9cf1-6e85c06d3972.png)
![lessons learned community mapping screenshot](https://cloud.githubusercontent.com/assets/17725960/16231153/f9977e34-3792-11e6-9d17-470a410ffa4a.png)
![coded content community mapping screenshot](https://cloud.githubusercontent.com/assets/17725960/16231176/16a078a0-3793-11e6-809d-3de2093ca3c0.png)

**Comment by andresgnlez** [comment]
Hi @shanikadhettige,

I just deployed the guide with latest changes. I am afraid in order to deploy, you will need to deal a little with the console (just a little, I promise).

When you merge new changes in `master` branch, be sure you have these changes locally running `git pull origin master` command. Once you have the new changes, it's time to deploy. 

To deploy, run the script `deploy.sh` running the command `./deploy.sh `. Once the script has ended successfully, you will be able to see new changes in http://vizzuality.github.io/community-mapping

That's all!

Let me know if you have problems!

**Comment by shanikadhettige** [comment]
@andresgnlez Following up on our email thread earlier, can you please deploy current changes?

Thanks!

**Comment by andresgnlez** [comment]
Yes, I just deploy. You can check new changes in the site!

If everything it's ok with push and pull access, let's close this issue. 

Thanks :)
